<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>LanceurRaccourcis</AssemblyName>
    <RootNamespace>LanceurRaccourcis</RootNamespace>
    <Nullable>enable</Nullable>
    <ApplicationIcon>icon.ico</ApplicationIcon>
	<OutputType>WinExe</OutputType>
    
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
	<StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.10" />
  </ItemGroup>

</Project>